### PR TITLE
Add more clarity on what an RFC is and is not

### PR DESCRIPTION
**Pull request by cart**
I think there is currently a bit of confusion about what constitutes an RFC, where design discussions should happen, etc. This attempts to add some clarity, without being overly prescriptive.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I like this. I think this could use some guidance on draft RFCs as well. Is opening up a draft RFC on a topic with the intent of fleshing it out with a full design Soon:tm: appropriate? I've been using this workflow to allow me to slowly and publicly refine designs.

Of course, I could always make branches for this on my fork and then delay opening a PR until they're largely complete, but I enjoy having the draft PRs open to signal my priorities and invite comment / initial review on what I have.

**Comment by cart** [comment]
> Is opening up a draft RFC on a topic with the intent of fleshing it out with a full design Soon appropriate? I've been using this workflow to allow me to slowly and publicly refine designs.

I think we should require a minimum amount of effort and detail to help start (and scope) the conversation, as well as to respect the attention of people subscribed to RFC repo notifications. We should discourage RFCs with a few sentences and TODOs everywhere. Imo if you can't describe the design and goals from a high level, draw out a first draft of the public apis, and prescribe a good portion of the technical details, you aren't ready for the RFC process yet.

**Comment by cart** [comment]
I think its important to have a bar, otherwise we will likely continue to see a bunch of highly ambitious RFCs with zero general direction created by people who haven't really considered the design space yet. RFCs should be a way for "thought leaders" to show us the way, not a place to blindly start discussing a subject.

**Comment by alice-i-cecile** [comment]
>  Imo if you can't describe the design and goals from a high level, draw out a first draft of the public apis, and prescribe a good portion of the technical details, you aren't ready for the RFC process yet.

Sounds good; I can get behind this. The clutter and noise are important. Can you add something to this effect to this PR?

On my end, I'll wait longer to submit draft PRs in the future. Internationalization and archetype invariants for example are not at this level yet; I'll aim to get them up to snuff over the next week or two. I have a reasonably clear vision for both, but they're going to require a fair bit of time and the UI work is higher priority.

**Comment by cart** [comment]
> Sounds good; I can get behind this. The clutter and noise are important. Can you add something to this effect to this PR?

Yeah thats a good call.

> On my end, I'll wait longer to submit draft PRs in the future. Internationalization and archetype invariants for example are not at this level yet; I'll aim to get them up to snuff over the next week or two. I have a reasonably clear vision for both, but they're going to require a fair bit of time and the UI work is higher priority.

Much appreciated. Also for clarity, this isn't intended to be critical and I consider you to be a "thought leader". I think a "faster and looser" RFC process has merits too and I certainly wasn't clear enough about my goals until now. I just want to (1) keep the signal:noise ratio in a good place and (2) encourage people to put in the work to build cohesive designs rather than just stake claims on spaces they are interested in, but haven't put the effort into yet.

I know you've put a lot of effort into your designs already / have a lot of cool stuff queued up, so in your case this should just be a matter of consolidating what you already have (when you have the time and inclination to do that).

**Pull request merged**
